In [70]:
import numpy as np
print(np.random.randint(1, 228, 13))

[132  56 114  69 170 209  93  45 107 157   4 192 209]


In [65]:
#создание массива c обыч списком
data = [2,2,8,6,6,6]
print("массив из списка", np.array(data))

массив из списка [2 2 8 6 6 6]


In [13]:
#создание массива из нулей
a = np.zeros(5)
print("массив из нулей", a)
a2 = np.zeros((3, 4))
print("двумеррный массив из нулей", a2)

массив из нулей [0. 0. 0. 0. 0.]
двумеррный массив из нулей [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
#создание массива из единиц
a = np.ones(5)
print("массив из единиц", a)
a2 = np.ones((3,3))
print("двумернйы массив из единиц", a2)

массив из единиц [1. 1. 1. 1. 1.]
двумернйы массив из единиц [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#массив с арандж
a = np.arange(0, 228, 4)  #от 0 до 228 с шагом 4
print(a)

[  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100 104 108 112 116 120 124 128 132 136 140
 144 148 152 156 160 164 168 172 176 180 184 188 192 196 200 204 208 212
 216 220 224]


In [20]:
#массив с линспейс
a = np.linspace(0, 1, 5)  # 5 чисел от 0 до 1
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [30]:
#атрибуты
a = np.zeros((3, 4))
print("shape" , a.shape)
print("Тип данных", a.dtype)
print("Размерность",a.ndim)
print("size", a.size)


shape (3, 4)
Тип данных float64
Размерность 2
size 12


In [37]:
#индексирование и срезы
#получаем отдельные элементы
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("исходный массив", a)
print(a[0]) #Первый элемент
print(a[-1]) #Последний элемент
print(a[5])#Элемент с индексом 5
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(matrix[1, 2]) #элемент 1,2
print(matrix[0, 0]) #элемент 0 0 

исходный массив [ 1  2  3  4  5  6  7  8  9 10]
1
10
6
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
1


In [43]:
#извлечение подмассива с помощью среза
alpha = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(alpha[:4]) #первые 4 элемента
print(alpha[6:]) #элементы с 6 до конца
print(alpha[::2]) #каждый второй элемент

[1 2 3 4]
[ 7  8  9 10]
[1 3 5 7 9]


In [52]:
#вектрные операции
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 8, 6, 6])
print(a + b) #сложение
print(a * b) #умножение и тд
#скаляры
print(a+10)
print(a*2)

[ 3  4 11 10 11]
[ 2  4 24 24 30]
[11 12 13 14 15]
[ 2  4  6  8 10]


In [63]:
#ьазовые статистические функции
data1488 = np.array([2, 2, 8, 6, 6, 6])
print(np.min(data1488)) #мин значение
print(np.max(data1488)) #макс значение
print(np.mean(data1488)) #ср значение
print(np.median(data1488)) #медиана
print(np.var(data1488)) #дисперсия
print(np.sum(data1488)) #сумма

2
8
5.0
6.0
5.0
